### ISSUE TITLE
Exception 

### ISSUE THREAD

**Issue by Assassin0002** [Fhoughton/Steam-Key-Sniper#2]
Traceback (most recent call last):
  File "C:\Users\X\Desktop\Steam-Key-Sniper-master\SteamKeySniper.py", line 110, in <module>
    CheckNew()
  File "C:\Users\X\Desktop\Steam-Key-Sniper-master\SteamKeySniper.py", line 71, in CheckNew
    r = praw.Reddit(user_agent = "Steam Key Scraper")
  File "C:\Users\X\AppData\Roaming\Python\Python39\site-packages\praw\reddit.py", line 250, in __init__
    raise MissingRequiredAttributeException(
praw.exceptions.MissingRequiredAttributeException: Required configuration setting 'client_id' missing.
This setting can be provided in a praw.ini file, as a keyword argument to the `Reddit` class constructor, or as an environment variable.

**Comment by kenx00x** [comment]
you need to make a praw.ini file check this link for more info

https://praw.readthedocs.io/en/latest/getting_started/configuration/prawini.html
